### PR TITLE
Directionalfocus

### PR DESCRIPTION
**Pull request by allora**
This adds support for cardinal window focusing. Users are able to pick a window to focus based on the closest window within the desired cardinal direction. 

For example a user sending the command: `waitron window_cardinal_focus up` will change the focused window to the one above the current window, if one exists and there is a current focused window. Testing on a triple head setup showed that the algorithm for window focus selection worked as expected across displays.

I've attempted to have "good defaults" for the window selection heuristics, but arguably they could be made into config settings instead, with a default in the config.h file.

I also added a group_remove_all_windows, which does what it sounds like it does. Removes all windows from a group.

### CODE REVIEW

**Comment by tudurom** [comment]
Wow, I am truly impressed. Thank you for the huge contribution. But there's a problem that isn't letting me merge the pr: you used a different code style. Please adapt your changes to the code style (opening brace on the same line as the statement, no C++ style comments etc.).

**Comment by allora** [comment]
Sorry about that, work habits :) Updated.

**Comment by tudurom** [comment]
Also, the `group_remove_all_windows` command removes all the windows from all the groups because there is no check. Your code iterates over all windows and removes the group.

**Comment by allora** [comment]
Updated. This is a total brain fart on my end O_o. In testing it, I don't think it was ever tested with multiple groups assigned haha.

**Comment by tudurom** [comment]
Thanks! I will add you to the "thanks to" section in the readme ;)

**Comment by allora** [comment]
Awesome! Thanks :)

**Pull request merged**
